[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=79

[tool.black]
line_length=79

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = true
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = false
fail-under = 100
exclude = ["setup.py", "docs", "build", "migrations"]
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*", "^test_.*", "^Meta", "step_impl"]
verbose = 1
quiet = false
whitelist-regex = []
color = true
